Repository cse110-sp25-group17/cse110-sp25-group17, pull requests merged in 2025-05, with the labels that each got.

#12 added issues feature to diagram
  admin/cipipeline/phase1.drawio.png
Labels: approval

#37 added codacy yaml files
  .codacy.yaml
  .github/workflows/codacy.yml
Labels: approval, ci/cd

#67 Verify pokemon lawrence
  source/scripts/app.js
  source/styles/style.css
Labels: backend
