Repository cse110-sp25-group17/cse110-sp25-group17, pull requests merged in 2025-06, with the labels that each got.

#159 Nickname sanitization and hover disable
  __tests__/sameName.test.js
  source/scripts/edit_page.js
  source/styles/style.css
Labels: enhancement, frontend, backend

#202 Fix Repeating Type and Improve Responsiveness
  assets/images/pokemon_logo.webp
  source/collection.html
  source/edit_page.html
  source/favicon.png
  source/form.html
  source/game_page.html
  source/home_page.html
  source/main_page.html
  source/scripts/collection.js
Labels: bug

#200 Changed the question to "Who's that Pokemon" to fit the theme and dec…
  __tests__/game.type.test.js
  source/scripts/game.js
  source/styles/style.css
Labels: frontend
